using AutoMapper;
using JobMarketplace.Application.Common.Models;
using JobMarketplace.Application.Features.Countries.Commands.CreateCountry;
using JobMarketplace.Domain.Entities;
using JobMarketplace.Domain.Interfaces;
using MediatR;
using System;
using System.Collections.Generic;
using System.Text;

namespace JobMarketplace.Application.Features.Skills.Commands.CreateSkill
{
    public class CreateSkillCommandHandler : IRequestHandler<CreateSkillCommand, Result<Guid>>
    {
        private readonly ISkillRepository _skillRepository;
        private readonly IMapper _mapper;

        public CreateSkillCommandHandler(ISkillRepository skillRepository, IMapper mapper)
        {
            _skillRepository = skillRepository;
            _mapper = mapper;
        }

        public async Task<Result<Guid>> Handle(CreateSkillCommand request, CancellationToken cancellationToken)
        {
            var skill = _mapper.Map<Skill>(request);

            // Id (BIGINT) and PublicGuid (GUID) are auto-generated by SQL Server

            await _skillRepository.AddAsync(skill, cancellationToken);
            await _skillRepository.SaveChangesAsync(cancellationToken);

            return Result<Guid>.Success(skill.PublicGuid);
        }
    }
}
