using AutoMapper;
using JobMarketplace.Application.Common.Models;
using JobMarketplace.Application.Features.Companies.Commands.CreateCompany;
using JobMarketplace.Domain.Entities;
using JobMarketplace.Domain.Interfaces;
using MediatR;
using System;
using System.Collections.Generic;
using System.Text;

namespace JobMarketplace.Application.Features.Countries.Commands.CreateCountry
{
    public class CreateCountryCommandHandler : IRequestHandler<CreateCountryCommand, Result<Guid>>
    {
        private readonly ICountryRepository _countryRepository;
        private readonly IMapper _mapper;

        public CreateCountryCommandHandler(ICountryRepository countryRepository, IMapper mapper)
        {
            _countryRepository = countryRepository;
            _mapper = mapper;
        }

        public async Task<Result<Guid>> Handle(CreateCountryCommand request, CancellationToken cancellationToken)
        {
            var country = _mapper.Map<Country>(request);

            // Id (BIGINT) and PublicGuid (GUID) are auto-generated by SQL Server

            await _countryRepository.AddAsync(country, cancellationToken);
            await _countryRepository.SaveChangesAsync(cancellationToken);

            return Result<Guid>.Success(country.PublicGuid);
        }
    }
}
